### ISSUE TITLE
when building css variables, how to add prefix to to every css variable

### ISSUE THREAD

**Issue by uptonking** [drwpow/cobalt-ui#21]
- the css variables names are easy to get conflicts in the examples.

- instead of current example

```css
:root {
  --color-black: #1b1f24;
  --color-blue0: #ddf4ff;
  --color-blue1: #b6e3ff;
}
```
- I want below
```css
:root {
  --ibm-color-black: #1b1f24;
  --ibm-color-blue0: #ddf4ff;
  --ibm-color-blue1: #b6e3ff;
}
```
